### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by chuckster97** [ibrews/UnofficialMetaHumanVR_Studio#2]
Failed to load map!
../../../../../pro/MetaHumanVRStudio/Content/Maps/Studio_Blue.umap appears to be an asset file.

**Comment by Nocxr** [comment]
Hey @chuckster97,

I tried replicating this on my end and was unable to get the same error, can you please shed a little more light on when/how you are receiving this error?

I cloned the repo to a new destination, grabbed the latest MetaXR plugin and dropped it into the plugins folder: (https://developer.oculus.com/downloads/package/unreal-engine-5-integration/) and it started right up.

The first thing that comes to mind is I see 5 subdirectories before I can see the path name in your error, maybe its a pathname being too long issue:

"Unreal Engine enforces a 180 character path limit for all source files and assets. However, Unreal will add its own long pathnames to that. The total path and filename length must not exceed 260 characters."

If this is not the case please let me know any other relevant info you can and I will try to get an answer for you asap!  

Thanks!

**Comment by chuckster97** [comment]
Honestly what version of unreal
Like the plugin is 5.2
I try to load and it gives the error message. I run unreal engine off the
root of d:\unreal engine\ver
Projects are e:\pro\project
The plugin works and loads when I create new project.
Do I not install to engine and only the project?
Even then it says wrong version and fails to build the plugin in

**Comment by chuckster97** [comment]
Downloaded and tried again to run using unreal 5.2.1  
changed folder and project to shorter names still error

**Comment by chuckster97** [comment]
Whatever the issue was is in the zip download 
I cloned the repo and it worked fine
Thanks for your response
